/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.calculator;

import java.io.IOException;
import java.net.URL;
import java.util.HashMap;

import edu.duke.ece651.calculator.controller.CalculatorController;
import edu.duke.ece651.calculator.controller.NumButtonController;
import edu.duke.ece651.calculator.model.RPNStack;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.ListView;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;

public class App extends Application {
  @Override
  public void start(Stage stage) throws IOException {
    // String javaVersion = System.getProperty("java.version");
    // String javafxVersion = System.getProperty("javafx.version");
    // Label l = new Label("Hello, JavaFX " + javafxVersion +
    // ", running on Java " +
    // javaVersion + ".");
    // Scene scene = new Scene(new StackPane(l), 640, 480);
    // ___________________java and java fx version______________________//

    // _______normal_java_code_to_display________________________//
    // GridPane gp = new GridPane();
    // String[] labels = new String[] { "+", "-", "*", "/",
    // "7", "8", "9",
    // "4", "5", "6",
    // "1", "2", "3",
    // "." };
    // int rows[] = new int[] { 0, 0, 0, 0,
    // 1, 1, 1,
    // 2, 2, 2,
    // 3, 3, 3,
    // 4 };
    // int cols[] = new int[] { 0, 1, 2, 3,
    // 0, 1, 2,
    // 0, 1, 2,
    // 0, 1, 2,
    // 2 };
    // for (int i = 0; i < labels.length; i++) {
    // Button b = new Button(labels[i]);
    // gp.add(b, cols[i], rows[i]);
    // b.setMaxWidth(Double.MAX_VALUE);
    // b.setMaxHeight(Double.MAX_VALUE);
    // }
    // Button b = new Button("0");
    // b.setMaxWidth(Double.MAX_VALUE);
    // b.setMaxHeight(Double.MAX_VALUE);
    // gp.add(b, 0, 4, 2, 1);
    // b = new Button("E\nn\nt\ne\nr");
    // b.setMaxWidth(Double.MAX_VALUE);
    // b.setMaxHeight(Double.MAX_VALUE);
    // gp.add(b, 3, 1, 1, 3);
    // for (int i = 0; i < 4; i++) {
    // ColumnConstraints cc = new ColumnConstraints();
    // cc.setPercentWidth(25);
    // gp.getColumnConstraints().add(cc);
    // }
    // for (int i = 0; i < 5; i++) {
    // RowConstraints rc = new RowConstraints();
    // rc.setPercentHeight(20);
    // gp.getRowConstraints().add(rc);
    // }

    // _______use____fxml_____________//
    RPNStack model = new RPNStack();
    URL xmlResource = getClass().getResource("/ui/calc-split.xml");
    FXMLLoader loader = new FXMLLoader(xmlResource);
    HashMap<Class<?>, Object> controllers = new HashMap<>();
    controllers.put(NumButtonController.class, new NumButtonController(model));
    controllers.put(CalculatorController.class, new CalculatorController());
    loader.setControllerFactory((c) -> {
      return controllers.get(c);
    });
    GridPane gp = loader.load();
    Scene scene = new Scene(gp, 640, 480);
    URL cssResource = getClass().getResource("/ui/calcbuttons.css");
    scene.getStylesheets().add(cssResource.toString());
    @SuppressWarnings("unchecked")
    ListView<Double> operands = (ListView<Double>) scene.lookup("#rpnstack");
    operands.setItems(model.getList());
    stage.setScene(scene);
    Thread.setDefaultUncaughtExceptionHandler(new ErrorReporter());
    stage.show();
  }
}
